"""Render the GRAPH_REPORT.md from a graph + analysis dict."""
from __future__ import annotations
import networkx as nx


def render_report(G: nx.Graph, analysis: dict) -> str:
    """Render a Markdown report from the analysis dict.

    Structure: header, god nodes, surprises, questions, communities.
    """
    out: list[str] = []
    out.append("# Graph Report\n")
    out.append(f"**{analysis['node_count']} nodes** · **{analysis['edge_count']} edges**\n")

    # Confidence distribution
    cd = analysis.get("confidence_distribution", {})
    if cd:
        parts = [f"{k}: {v}" for k, v in sorted(cd.items(), key=lambda x: -x[1])]
        out.append(f"Confidence: {' · '.join(parts)}\n")

    # God nodes
    out.append("\n## God nodes (most-connected entities)\n")
    if analysis["god_nodes"]:
        out.append("These are the most-connected real entities -- usually core abstractions.\n")
        for g in analysis["god_nodes"]:
            src = g.get("source_file", "")
            src_short = src.split("/")[-1] if src else ""
            out.append(f"- **{g['label']}** (degree {g['degree']}) -- `{src_short}`")
    else:
        out.append("_No god nodes detected (graph too small)._")

    # Surprising connections
    out.append("\n\n## Surprising connections\n")
    out.append("Connections between things that live in different files/modules.\n")
    if analysis["surprising_connections"]:
        for s in analysis["surprising_connections"]:
            reasons = " · ".join(s["reasons"]) if s["reasons"] else "--"
            out.append(
                f"- **{s['source_label']}** --`{s['relation']}`-> **{s['target_label']}** "
                f"_(score {s['score']}, {s['confidence']})_  \n  {reasons}"
            )
    else:
        out.append("_No cross-file surprises in this corpus._")

    # Communities
    if analysis.get("communities"):
        out.append("\n\n## Communities (subsystems)\n")
        out.append("Detected by Leiden/Louvain. Largest first.\n")
        for c in analysis["communities"]:
            sample = ", ".join(c["sample_labels"][:5])
            out.append(f"- **Community {c['id']}** ({c['size']} nodes) -- {sample}")

    # Suggested questions
    out.append("\n\n## Suggested questions\n")
    out.append("Questions this graph is uniquely positioned to answer:\n")
    for q in analysis["suggested_questions"]:
        out.append(f"- {q}")

    out.append("\n\n---\n\n_Generated by pocket-graph._\n")
    return "\n".join(out)


__all__ = ["render_report"]
